modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Darkorg69/BetterPunching/issues" #optional

[[mods]] #mandatory
modId="betterpunching" #mandatory
version="1.7.0-1.16.5" #mandatory
displayName="Better Punching" #mandatory
#updateJSONURL="" #optional
displayURL="https://github.com/Darkorg69/BetterPunching" #optional
logoFile="betterpunching.png" #optional
credits="Thanks for this mod goes to Java and the Forge team." #optional
authors="Darkorg" #optional
description='''A mod, overhauling punching and breaking mechanics in a popular block game!'''

[[dependencies.betterpunching]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.betterpunching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
