modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="GNU LGPLv3"
#issueTrackerURL="" #optional

[[mods]] #mandatory
modId="betterpunching" #mandatory
version="1.2.0-1.18.1" #mandatory
displayName="Better Punching" #mandatory
#updateJSONURL="" #optional
#displayURL="" #optional
logoFile="betterpunching.png" #optional
credits="Thanks for this mod goes to Java and the Forge team." #optional
authors="Darkorg" #optional
description='''A mod, overhauling punching and breaking mechanics in a popular block game!'''

[[dependencies.betterpunching]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.betterpunching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
