modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Darkorg69/BetterPunching/issues" #optional

[[mods]] #mandatory
modId="betterpunching" #mandatory
version="1.16.5-1.6.0" #mandatory
displayName="Better Punching" #mandatory
#updateJSONURL="https://github.com/Darkorg69" #optional
displayURL="https://github.com/Darkorg69/BetterPunching" #optional
logoFile="betterpunching.png" #optional
credits="Java and the Forge team for making this mod possible." #optional
authors="Darkorg" #optional
description='''A mod, overhauling punching and breaking mechanics in a popular block game!''' #mandatory

[[dependencies.betterpunching]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.betterpunching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
